version: '3'

services:
  db:
    image: mysql:latest
    ports: 
      - "33061:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=D3v3l@p3r
      - MYSQL_DATABASE=GeoApp
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=D3v3l@p3r

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5436
    volumes:
      - .:/code
    ports:
      - "5436:5436"
    depends_on:
      - db
    
