# Generated by Django 4.0.4 on 2022-05-28 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='usernames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_company_author_usernames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
