# Generated by Django 4.0.4 on 2022-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateField(blank=True, null=True, verbose_name='last_login'),
        ),
    ]
